# Site
name: 'Winter Zone'
description: 'Learn everything, just don't give up. 酌贪泉而觉爽，处涸辙以犹欢'
logo: 'assets/images/mylogo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/yldblog'
disqus: 'demowebsite'
email: 'aiyld@hotmail.com'
mailchimp-list: 'https://www.samyoc.com/yoc/message?action=subscribe'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

articletypes: ["article", "quote", "video", "gallery", "audio", "link"]

authors:
    yld:
      name:           Winter
      link:           author-yld
      site:           https://www.winterccc.com
      avatar:         assets/images/mylogo.png
      bio:            "Winter is coming"
      email:          aiyld@hotmail.com
      twitter:        https://twitter.com/yang_ld
      sina:           https://weibo.com/myyld

socials:
  samyoc:
    name: "samyoc"
    url: "https://www.samyoc.com/home/1"
  facebook:
    name: "facebook"
    url: "https://www.facebook.com/winteryld"
  weibo:
    name: "微博"
    url: "https://weibo.com/myyld"
  github:
    name: "GitHub"
    url: "https://github.com/aiyld"
  twitter:
    name: "Twitter"
    url: "https://twitter.com/yang_ld"
 
rewards:
  btc:
    name: BTC
    addr: "1Q6ZDFC3FueXY3JocmeMqgiSsGGtppbvz2"
    logo: 'assets/images/btc.png'
    qr: 'assets/images/btc-qr.png'
  bch:
    name: BCH(CashAddr)
    addr: "qpa3lmppzg2zz3n53s9x7yeanparkeplwudhqa89g8"
    logo: 'assets/images/bch.jpg'
    qr: 'assets/images/bch-qr.png'
  ETH:
    name: ETH
    addr: "0xff6FC30033269845d196cB48F6a0660598D218D8"
    logo: 'assets/images/eth.png'
    qr: 'assets/images/eth-qr.png'

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: yld
      avatar: assets/images/mylogo.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 16



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
