# Site
name: 'YLD'
description: 'YLD的个人网站。YLD，又名Winter，冬天降生的BOY，天真执着的程序员，技术宅，技术痴，努力逆天改命者。'
logo: 'assets/images/mylogo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: 'demowebsite'
email: 'aiyld@hotmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    yld:
      name:           YLD
      site:           https://www.yanglidong.com
      avatar:         assets/images/mylogo.png
      bio:            "Hi, 我是YLD，也可以叫我Winter，冬天降生的Boy。一个天真执着的程序员，遨游于代码的星辰大海!"
      email:          aiyld@hotmail.com
      twitter:        https://twitter.com/yang_ld
      sina:           https://weibo.com/myyld
 
rewards:
  btc:
    name: BTC
    addr: "17LB9ZCzvbGDZzYoUV2RPTX3E88y7pxthi"
    logo: 'assets/images/btc.png'
  bch:
    name: BCH
    addr: "17LB9ZCzvbGDZzYoUV2RPTX3E88y7pxthi"
    logo: 'assets/images/bch.jpg'
  ETH:
    name: ETH
    addr: "0x2b3246b2f13e586839d9dcb173f5c6cffaf46930"
    logo: 'assets/images/eth.png'

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: yld
      avatar: assets/images/mylogo.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]